[workspace]
members = ["yokoi-tui"]

[package]
name = "yokoi"
version = "0.1.0"
edition = "2024"
description = "A gameboy emulation library."
license = "MIT"

[dependencies]
bytemuck = "1.25.0"
enumset = "1.1.10"
thiserror = "2.0.18"
